### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by phoenix214**
Added Arabic translation and fixed English error.
This is mandatory to make the latest version 0.3.3 work.

### CODE REVIEW

**Comment by arochedy** [comment]
There is no file modified ?

**Comment by phoenix214** [comment]
Sorry, I just added it. @arochedy

**Comment by arochedy** [comment]
The problem was just because it was missing an arabic translation ?

**Comment by phoenix214** [comment]
Yes.

**Review by arochedy — APPROVED** [review]

**Review by perscrew — APPROVED** [review]

**Comment by perscrew** [comment]
PR has been merged. I'm going to publish a new version in the morning.

**Pull request merged**
